name: class_link
description: A new Flutter project.
publish_to: none

version: 0.1.32+34

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.7
  # awesome_notifications: ^0.7.4+1
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.8.3
  firebase_analytics: ^10.4.4
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flex_color_scheme: ^7.1.2
  flutter_custom_tabs: ^1.0.4
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  get: ^4.6.5
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.4
  hive_flutter: ^1.1.0
  paged_vertical_calendar: ^1.1.6
  share_plus: ^7.0.2
  url_launcher: ^6.1.12
  in_app_review: ^2.0.6
  day_night_time_picker: ^1.3.0
  in_app_update: ^4.1.4
  csv: ^5.0.2
  package_info_plus: ^5.0.1

  gsheets:
    git:
      url: https://github.com/4-alok/gsheets.git
      ref: henri2h/update-dep
  sticky_grouped_list: ^3.1.0
  hidable: ^1.0.4
  grouped_list: ^5.1.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  hive: ^2.2.3
  intl: ^0.19.0

dev_dependencies:
  freezed: ^2.4.2
  flutter_native_splash: ^2.3.1

  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/database/3rd_year/
    - assets/svg/

# ================================================

flutter_native_splash:
  image: assets/icons/app_logo.png
  color_dark: "#191919"
  android_12:
  color_dark_android: "#042a49"
