name: class_link
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.14.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flutter_svg: ^0.23.0+1
  get: ^4.3.8
  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  google_sign_in: ^5.2.1
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true

