name: class_link
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.14.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flutter_svg: ^0.23.0+1
  get: ^4.3.8
  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  google_sign_in: ^5.2.1
  cloud_firestore: ^2.5.3
  freezed_annotation: ^0.15.0
  json_annotation: ^4.3.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  meta: ^1.7.0
  cached_network_image: ^3.1.0+1
  font_awesome_flutter: ^9.2.0
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  build_runner: ^2.1.4
  freezed: ^0.15.1+1
  json_serializable: ^6.0.1
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
