name: class_link
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.4
  google_fonts: ^2.1.1
  flutter_svg: ^1.0.0
  get: ^4.6.1
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  google_sign_in: ^5.2.1
  cloud_firestore: ^3.1.5
  freezed_annotation: ^1.1.0
  json_annotation: ^4.3.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  meta: ^1.7.0
  cached_network_image: ^3.1.0+1
  font_awesome_flutter: ^9.2.0
  implicitly_animated_reorderable_list: ^0.4.2
  animations: ^2.0.2
  vibration: ^1.7.4-nullsafety.0
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  build_runner: ^2.1.4
  freezed: ^1.1.0
  json_serializable: ^6.0.1
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
