const electiveTeachers = {
  "ML_CS-1": "Dr. Rajdeep Chatterjee",
  "ML_CS-2": "Mr. Debanjan Pathak",
  "ML_CS-3": "Dr. M. Nazma B. J. Naskar",
  "ML_CS-4": "Dr. Rina Kumari",
  "ML_CS-5": "Mr. Abinas Panda",
  "ML_CS-6": "Ms. Jayeeta Chakraborty",
  "ML_CS-7": "Prof. T. Kar",
  "ML_CS-8": "Prof.. Pravin Samanta",
  "ML_CS-9": "Prof. Bhargav Appasani",
  "ML_CS-10": "Dr. Subrat Kumar Barik",
  "ML_CS-11": "Dr. Babita Panda",
  "ML_CS-12": "Prof. Soubhagya Ranjan Prusty",
  "ML_CS-13": "Prof. Subodh Ku Mohanty",
  "ML_CS-14": "Mr. Joy Dutta",
  "IOT_CS-1": "Mr. Joy Dutta",
  "IOT_CS-2": "Dr. Chitralekha Jena",
  "IOT_CS-3": "Dr. Arjyadhara Pradhan",
  "IOT_CS-4": "Dr. Sarita Samal",
  "IOT_CS-5": "Prof. Ankit Kumar Soni",
  "IOT_CS-6": "Mrs. Lipika Mohanty",
  "NLP_CS-1": "Mrs. Lipika Dewangan",
  "NLP_CS-2": "Dr. Partha Sarathi Paul",
  "NLP_CS-3": "Mrs. Lipika Dewangan",
  "DA_CS-1": "Dr. Hrudaya Kumar Tripathy",
  "DA_CS-2": "Dr. Mainak Bandyopadhyay",
  "DA_CS-3": "Dr. Sarita Tripathy",
  "DA_CS-4": "Dr. Satarupa Mohanty",
  "DA_CS-5": "Dr. Minakhi Rout",
  "DA_CS-6": "Mr. Ajay Anand",
  "DA_CS-7": "Dr. Ambika Prasad Mishra",
  "DA_CS-8": "Mr. Ajay Anand",
  "DA_CS-9": "Dr. Soumya Ranjan Mishra",
  "DA_CS-10": "Mrs. Jayanti Dansana",
  "DA_CS-11": "Dr. Arup Abhinna Acharya",
  "DA_CS-12": "Dr. Arup Abhinna Acharya",
  "DA_CS-13": "Dr. Soumya Ranjan Mishra",
  "DA_CS-14": "Dr. Jagannath Singh",
  "DA_CS-15": "Mrs. Jayanti Dansana",
  "DA_CS-16": "Dr. Sarita Tripathy",
  "DA_CS-17": "Dr. Ambika Prasad Mishra",
};
