const electiveTeachers = {
  "CRP_CS-1": "Dr. Chittaranjan Pradhan",
  "CRP_CS-2": "Mr. A Ranjith",
  "CRP_CS-3": "Mr. Chandra Shekhar",
  "AI_CS-1": "Mr. Ramesh Kumar Thakur",
  "AI_CS-2": "Ms. Santwana Sagnika",
  "AI_CS-3": "Mr. N. Biraja Isac",
  "AI_CS-4": "Dr. Mainak Bandyopadhyay",
  "AI_CS-5": "Mr. Sunil Kumar Gouda",
  "AI_CS-6": "Mr. Debanjan Pathak",
  "AI_CS-7": "Dr. Rina Kumari",
  "AI_CS-8": "Dr. Partha Sarathi Paul",
  "AI_CS-9": "Dr. Madhabananda Das",
  "AI_CS-10": "Mr. Ajay Anand",
  "AI_CS-11": "Mr. Debanjan Pathak",
  "AI_CS-12": "Mr. Ramesh Kumar Thakur",
  "AI_CS-13": "Mr. Subhadip Pramanik",
  "AI_CS-14": "Mr. N. Biraja Isac",
  "AI_CS-15": "Dr. Pampa Sinha",
  "AI_CS-16": "Dr. Rajdeep Chatterjee",
  "AI_CS-17": "Mr. Subhadip Pramanik",
  "AI_CS-18": "Dr. Banhi Sanyal",
  "AI_CS-19": "Mr. Ajay Anand",
  "AI_CS-20": "Dr. Mainak Bandyopadhyay",
  "AI_CS-21": "Dr. Madhabananda Das",
  "AI_CS-22": "Ms. Pratyusa Mukherjee",
  "AI_CS-23": "Mr. Anirban Bhattacharjee",
  "AI_CS-24": "Mrs. Subhashree Darshana",
  "AI_CS-25": "Mr. Sourav Kumar Giri",
  "AI_CS-26": "Mr. Sunil Kumar Gouda",
  "AI_CS-27": "Dr. Satya Champati Rai",
  "AI_CS-28": "Dr. Padarabinda Samal",
  "AI_CS-29": "Dr. Nibedan Panda",
  "AI_CS-30": "Ms. Pratyusa Mukherjee",
  "AI_CS-31": "Dr. Debajyoty Banik",
  "AI_CS-32": "Mr. Jaydeep Das",
  "AI_CS-33": "Dr. Nibedan Panda",
  "AI_CS-34": "Mr. Sourav Kumar Giri",
  "AI_CS-35": "Dr. Rina Kumari",
  "AI_CS-36": "Mr. Anirban Bhattacharjee",
  "AI_CS-37": "Ms. Susmita Das",
  "AI_CS-38": "Dr. Banhi Sanyal",
  "BD_CS-1": "Mrs. Naliniprava Behera",
  "BD_CS-2": "Dr. Siddharth Swarup Rautaray",
  "BD_CS-3": "Dr. Anjan Bandyopadhyay",
  "BD_CS-4": "Dr. Suchismita Rout",
  "BD_CS-5": "Dr. Bhaswati Sahoo",
  "BD_CS-6": "Dr. Mainak Bandyopadhyay",
  "BD_CS-7": "Ms. Ipsita Paul",
  "BD_CS-8": "Mrs. Subhashree Darshana",
  "BD_CS-9": "Ms. Krutika Verma",
  "BD_CS-10": "Dr. Sourajit Behera",
  "BD_CS-11": "Dr. Arghya Kundu",
  "BD_CS-12": "Dr. Rajat Kumar Behera",
  "BD_CS-13": "Dr. Manjusha Pandey",
  "BD_CS-14": "Dr. Subhranshu Sekhar Tripathy",
  "BD_CS-15": "Ms. Krutika Verma",
  "BD_CS-16": "Dr. Sourajit Behera",
  "BD_CS-17": "Dr. Kumar Devadutta",
  "BD_CS-18": "Mrs. Jayanti Dansana",
  "BD_CS-19": "Dr. Sarita Tripathy",
  "BD_CS-20": "Dr. Jay Sarraf",
  "BD_CS-21": "Mrs. Subhashree Darshana",
  "BD_CS-22": "Dr. Arghya Kundu",
  "BD_CS-23": "Ms. Ipsita Paul",
  "BD_CS-24": "Dr. Sarita Tripathy",
  "BD_CS-25": "Dr. Bhaswati Sahoo",
  "BD_CS-26": "Dr. Suchismita Rout",
  "BD_CS-27": "Dr. Siddharth Swarup Rautaray",
  "BD_CS-28": "Dr. Subhranshu Sekhar Tripathy",
  "BD_CS-29": "Dr. Rajat Kumar Behera",
  "DMDW_CS-1": "Dr. Hrudaya Kumar Tripathy",
  "DMDW_CS-2": "Dr. Ajay Kumar Jena",
  "DMDW_CS-3": "Dr. Amiya Ranjan Panda",
  "DMDW_CS-4": "Dr. Himansu Das",
  "DMDW_CS-5": "Dr. Satarupa Mohanty",
  "DMDW_CS-6": "Dr. Murari Mandal",
  "CI_CS-1": "Dr. Partha Pratim Sarangi",
  "CI_CS-2": "Dr. Dipti Dash",
  "CI_CS-3": "Dr. Dayal Kumar Behera",
  "CI_CS-4": "Dr. Dipti Dash",
  "CI_CS-5": "Dr. Partha Pratim Sarangi",
  "CI_CS-6": "Dr. Dayal Kumar Behera",
  "DMDW_IT-1": "Dr. Ajay Kumar Jena",
  "DMDW_IT-2": "Dr. Hrudaya Kumar Tripathy",
  "DMDW_IT-3": "Dr. Sarita Tripathy",
  "CRP_IT-1": "Dr. Tanmoy Maitra",
  "CI_IT-1": "Mr. Sovan Kumar Sahoo",
  "BD_IT-1": "Dr. KVVSR Chowdary",
  "BD_IT-2": "Mr. Ajit Kumar Pasayat",
  "BD_IT-3": "Dr. KVVSR Chowdary",
  "AI_CE-1": "Dr. Ajaya Kumar Parida",
  "AI_CE-2": "Ms. Susmita Das",
  "ITC_CE-1": "Prof. M. Behera",
  "ITC_CE-2": "Prof. M. Behera",
  "NLP_SE-1": "Dr. Debajyoty Banik",
  "CI_SE-1": "Mr. Sovan Kumar Sahoo",
  "ML_SE-1": "Dr. Subrat Kumar Barik",
  "ML_SE-2": "Dr. Babita Panda",
};
